### ISSUE TITLE
Operator doesn't reconcile if the bucket/policybinding already exists

### ISSUE THREAD

**Issue by codestation** [benfiola/minio-operator-ext#28]
In my case i already had some buckets/policies created, then added manifests for the existing ones and more for the new ones that intended to create.

The new ones are created without a problem, but the existing ones always fail since minio reports that they already exists. For example:

```
time=2024-11-28T15:16:27.473Z level=ERROR msg="Reconciler error" name=operator controller=miniobucket controllerGroup=bfiola.dev controllerKind=MinioBucket MinioBucket.name=test-bucket MinioBucket.namespace=minio namespace=minio name=test-bucket reconcileID=b788f5c3-c57e-4a15-9d79-c25a755bee32 err="Your previous request to create the named bucket succeeded and you already own it.
```

```
time=2024-11-28T15:18:59.855Z level=ERROR msg="Reconciler error" name=operator controller=miniopolicybinding controllerGroup=bfiola.dev controllerKind=MinioPolicyBinding MinioPolicyBinding.name=test-policy MinioPolicyBinding.namespace=minio namespace=minio name=test-policy reconcileID=c6dcdf2d-d2f9-4d5d-9299-e3243e96b593 err="The specified policy change is already in effect. (Specified policy update has no net effect)"
```

I am not sure if the policies also have this problem because they fail with another error:

```
time=2024-11-28T15:19:03.343Z level=ERROR msg="Reconciler error" name=operator controller=miniopolicy controllerGroup=bfiola.dev controllerKind=MinioPolicy MinioPolicy.name=test-policy MinioPolicy.namespace=minio namespace=minio name=test-policy reconcileID=30bf723a-0d8c-4ef7-b3f6-9058b35d86ed err="invalid version '2012-10-17T00:00:00Z'"
```

My manifests are the following:

```
apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: test-bucket
spec:
  deletionPolicy: IfEmpty
  name: test-bucket
  tenantRef:
    namespace: minio
    name: minio
---
apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: test-user
spec:
  accessKey: test
  secretKeyRef:
    name: test-user
    key: AWS_SECRET_ACCESS_KEY
  tenantRef:
    namespace: minio
    name: minio
---
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: test-policy
spec:
  name: test-access
  statement:
    - effect: "Allow"
      action:
        - "s3:*"
      resource:
        - "arn:aws:s3:::test-bucket/*"
        - "arn:aws:s3:::test-bucket"
  tenantRef:
    namespace: minio
    name: minio
  version: 2012-10-17
---
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: test-policy
spec:
  policy: test-access
  tenantRef:
    namespace: minio
    name: minio
  user:
    builtin: test
```

The operator should handle those cases and expect that some resources could be already in there, else apply the changes needed so they are the same as their manifest.

**Comment by benfiola** [comment]
Thinking a little more about this, an unintended consequence of this is that the operator will allow duplicate resources.

For example, several MinioBucket resources could point to the same bucket.  Currently, allowing minio to fail when a bucket exists prevents this from happening.  If all MinioBucket resources think they ‘own’ the underlying bucket, deleting any of these resources will potentially delete that underlying bucket.

I personally don’t think this would be desirable behavior

**Comment by codestation** [comment]
> For example, several MinioBucket resources could point to the same bucket
This shouldn't be a validation error? The bucket name should be unique for the same tenantRef. Same with users (accessKey) and policies.

I opened the issue because i am not clear on how to handle a migration where an user (me) already has buckets/users/policies in place and want to convert those to declarative manifests. I guess i could delete all users and policies and let the operator recreate them (this would cause a brief downtime for affected services), but i cannot do that with buckets because they have multiple TB of data. 

Maybe adding a flag like `inheritExisting: true` to the CRDs to give the OK to the operator to grab the existing resources for itself.

**Comment by benfiola** [comment]
> This shouldn't be a validation error? The bucket name should be unique for the same tenantRef. Same with users (accessKey) and policies.

Yes, however the operator currently doesn't implement admission webhooks and is incapable of performing pre-submission validation.  (- though this is something I'd like to do soon!).  

Currently, we keep track of whether a kubernetes resource reconciled  successfully, and treat errors like 'minio bucket already exists' as reconciliation failures.  If I create four identical `MinioBucket` resources - one will reconcile successfully and create the bucket, meanwhile the three others will fail to reconcile.  It's not perfect ... but in the absence of admission webhooks, I think it works reasonably well.

> I opened the issue because i am not clear on how to handle a migration where an user (me) already has buckets/users/policies in place and want to convert those to declarative manifests. I guess i could delete all users and policies and let the operator recreate them (this would cause a brief downtime for affected services), but i cannot do that with buckets because they have multiple TB of data.

Yeah, I think that there should be a better story around migration than what currently exists ...

> Maybe adding a flag like inheritExisting: true to the CRDs to give the OK to the operator to grab the existing resources for itself.

... and I think this is a great idea!  I'll get something going ASAP - thanks for the suggestion!

**Comment by benfiola** [comment]
Alright, I've opened a PR that should hopefully address the use case you've pointed out.  For any of the resources the operator watches, you can now set `.spec.migrate` to _true_ to tell the operator that it can manage Minio objects that already exist.  Once the operator starts managing the resource, it will automatically unset/remove this field.

> I am not sure if the policies also have this problem because they fail with another error ...

It appears that YAML will treat date strings like [timestamps](https://yaml.org/spec/1.2.2/#example-timestamps) unless their quoted - which means my _MinioPolicy_ example manifest was bad (- particularly, the `.spec.version` field).  This PR additionally updates the example manifest to quote the `.spec.version` field of the _MinioPolicy_.

Even though my end-to-end integration tests look good, I'll probably integrate these changes tomorrow after doing some additional manual testing.

**Comment by benfiola** [comment]
Alright, I've integrated the changes into helm chart version `2.3.0-rc.1`.  When you get the chance, please let me know if the updated helm charts for the operator + CRDs handle your use cases.  (NOTE: you'll need to use `--devel --version 2.3.0-rc.1` when issuing your helm commands).

Also, for peace of mind - you could probably set up [bucket replication](https://min.io/docs/minio/linux/administration/bucket-replication.html) to backup your bucket data as an extra precaution.  There's no real risk here, but any workflows involving existing data always makes me extra wary.

**Comment by codestation** [comment]
Hi, tested the new version and it works fine (and quoting the .spec.version fixed the policies), just there is a problem with the "migrate" field.

> Once the operator starts managing the resource, it will automatically unset/remove this field.

The problem with this is that affects tools like ArgoCD that allow to declare the state of the cluster and will sync the resources until they match the ones in the cluster. In my case ArgoCD will add the `migrate` flag, then the operator removes it, triggering a sync operation in ArgoCD that will add the field again, then the operator removes it, and so on.

**Comment by benfiola** [comment]
Glad it (looks like it) works!

Apologies that it's less-than-ergonomic.  Because the _migrate_ field effectively overrides a 'safety feature' of the operator's resource lifecycle - I wanted to discourage leaving this field permanently on a resource.  Instead, it made more sense to have this be an ad-hoc patch/edit to an existing resource that says 'just this once, ignore the existence checks'.

---

With that in mind, you can get things working with ArgoCD by doing the following.  

1. Define the _MinioBucket_ resource in your infrastructure-as-code _without_ the '.spec.migrate` field set.
2. Customize ArgoCD at the [system level]((https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration) to ignore differences in the '.spec.migrate' field.  Here's what that configuration might look like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  ...
  name: argocd-cm
  namespace: argocd
data:
  ...
  resource.customizations.ignoreDifferences.bfiola.dev_MinioBucket: |-
    jqPathExpressions:
    - '.spec.migrate'
```
3. Patch or edit the _MinioBucket_ resource (via `kubectl edit` or something similar) to set`.spec.migrate` for the existing resource to perform a one-time migration.

---

Hopefully the above isn't unreasonable - let me know what you think!

**Comment by codestation** [comment]
I went with the ArgoCD config at the application level for now, but i will switch to the system level one once my config grows.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   ...
spec:
  ignoreDifferences:
  - group: bfiola.dev
    kind: "*"
    jqPathExpressions:
      - .spec.migrate

```
