### ISSUE TITLE
Use structured tenant references for minio resources

### ISSUE THREAD

**Issue by benfiola** [benfiola/minio-operator-ext#3]
Currently, all minio resources accept a `tenant` field in the form of `<namespace>/<name>`.  Within IaC projects where resources might be dynamically named or created, this means that the `tenant` field itself needs to be computed in an extra step.  (e.g., `tenant = resource.namespace + "/" + resource.name`).  To simplify things a bit, maybe we use properly structured tenant references instead - like `tenantRef` in the following example:

```
apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: test
spec:
  name: test
  tenantRef: 
    namespace: minio-23b8d64e
    name: minio
```

Thoughts?
