### ISSUE TITLE
Update `securityContext` to run under a `restricted` namespace

### ISSUE THREAD

**Issue by sdwilsh** [benfiola/minio-operator-ext#34]
The minio-operator manfiest will create a namespace with the label `pod-security.kubernetes.io/enforce: restricted`, which means the helm chart won't run in the same namespace without adding this to the values:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
```

Instead of having everyone do this manually, I think the helm chart offered here should just do this by default (things seem to run fine).
