### ISSUE TITLE
Ability to manage idp ldap policy bindings for user and group

### ISSUE THREAD

**Issue by redtex** [benfiola/minio-operator-ext#4]
I have minio tenant configured for LDAP authentication. So, we need to make LDAP user and LDAP group policy bindings.

I think it should be extension to MinioPolicyBinding object - add additional "group" property, which will be alternative to "user".

**Comment by benfiola** [comment]
I've created a [PR](https://github.com/benfiola/minio-operator-ext/pull/8) to update the `MinioPolicyBinding` resource to accept a `group` field as well - hopefully this covers what's being asked here!

**Comment by redtex** [comment]
Sorry for late answer - I'm on vacation.
Great - group policy for ipd ldap can be added and deleted. 
But when I try to delete MinioPolicyBinding for LDAP user, there is error in log:

<pre>
2024-06-19 07:08:42,473 - ERROR - minio_operator_ext.operator - on_policy_binding_delete:minio-hdd-tenant/user-to-policy failed with retryable error: admin request failed; Status: 404, Body: {"Code":"XMinioAdminNoSuchUser","Message":"The specified user does not exist. If you meant a user in LDAP, use `mc idp ldap` (Specified user does not exist. If you meant a user in LDAP please use command under `mc idp ldap`)","Resource":"/minio/admin/v3/idp/builtin/policy/detach","RequestId":"17DA56247588A4C9","HostId":"f61cc7ec9839268967 4268b333f3d51dc3108ea9bad0007bb3e969a03d6a8cf9"}
</pre>

There is same error, when I try to make it with `mc admin policy detach` command. With `mc idp ldap policy detach` - there is no problem.
So, in the operator rather must be logic, which detects kind of idp, or additional parameter in MinioPolicyBinding object which indicates what idp been used - internal, ldap or openid.

**Comment by benfiola** [comment]
Apologies for the delay - have been recently working on:

* Automating deployments
* Using a shared [operator-core](https://github.com/benfiola/operator-core) to reduce the amount of boilerplate for resource reconciliation

Will take a look at your follow up comment and see if I can repro and fix things shortly!

**Comment by benfiola** [comment]
So, MinIO disables operating against builtin identities when an identity provider is configured.  While the standard `policy attach` APIs _did_ work with LDAP groups and users - maybe this was accidental.  Attempting to operate against LDAP identities via the CLI (`mc admin policy attach`) doesn't work, and as you noticed, using the standard `policy detach` APIs doesn't not work with LDAP identities either. 

Because MinIO appears to want you to interact with policies _through_ your identity provider ...

> ... additional parameter in MinioPolicyBinding object which indicates what idp been used - internal, ldap or openid.

... I think you're right here - we'll probably want to specify the _type_ of identity in our policy bindings.  As a result, the policy binding custom resource will need to change.  Here's what I'm thinking:

```yaml
---
# ldap user
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
...
  user:
    ldap: user
---
# ldap group
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
...
  group:
    ldap: "cn=group,dc=example,dc=org"
---
# 'builtin' user (e.g., one created by MinioUser)
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
...
  user:
    builtin: user
---
# 'builtin' group (e.g., one created by MinioGroup)
apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
...
  group:
    builtin: ldap-group
```

Created the following [PR}(https://github.com/benfiola/minio-operator-ext/pull/13) that implements these changes.
